postingPlatforms:
  linkedIn:
    enabled: false
  squarespace:
    enabled: true
  medium:
    enabled: false
  facebook:
    enabled: false
  instagram:
    enabled: true
  twitter:
    enabled: false
