postingPlatforms:
  mailchimp:
    enabled: false
  linkedIn:
    enabled: true
  squarespace:
    enabled: false
  medium: 
    enabled: false
  facebook:
    enabled: false
  instagram:
    enabled: false
  twitter:
    enabled: false
