postingPlatforms:
  instagram:
    enabled: false
  linkedIn:
    enabled: false
  squarespace:
    enabled: false
  twitter:
    enabled: false

# one issue atm is that the config file structure is being overwritten in the main file